version: "3.9"

services:
  nginx_proxy:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=blue-v1
    ports:
      - "8081:8081"

  app_green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=green-v1
    ports:
      - "8082:8082"
